name: Jest

on: [ push ]

jobs:
  implant: 
    runs-on: ubuntu-latest
    environment: secrets
    env: 
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_USER: ${{ secrets.DB_USER }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      ENVIROMENT: ${{ secrets.ENVIROMENT }}
      EMAIL_CREDENTIAL: ${{ secrets.EMAIL_CREDENTIAL }}
    steps:
      - name: Create
        run: echo -e DB_USER='"$DB_USER"\n'JWT_SECRET='"$JWT_SECRET"\n'DB_PASS='"$DB_PASS"\n'ENVIROMENT='"$ENVIROMENT"\n' > .env
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  
      - run: npm i
      - run: npm run dev & 
      - run: npm run test:force